server:
  port: 8080

spring:
  application:
    name: search-analytics-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000

elasticsearch:
  url: ${ELASTICSEARCH_URL:http://elasticsearch:9200}
  products-index: portfolio-products
  variants-index: portfolio-variants

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
