server:
  port: 8080

spring:
  application:
    name: sales-analytics-service
  influx:
    token: ${SPRING_INFLUX_TOKEN:my-super-secret-auth-token}
    bucket: ${SPRING_INFLUX_BUCKET:sales_analytics_bucket}
    org: ${SPRING_INFLUX_ORG:nais_org}
    url: ${SPRING_INFLUX_URL:http://influxdb:8086}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
